- scalable
  - 发音
    - 英 /ˈskeɪ.lə.bəl/
    - 美 /ˈskeɪ.lə.bəl/
  - 词义
    - adj. 可扩展的；可伸缩的
      - capable of being scaled or expanded to accommodate growth or increase in demand
  - 记忆
    - scale(规模) + able(能够) → 能够扩展的 → 可扩展的
  - 同根词
    - n. scalability 可扩展性
  - 近义词
    - adaptable 可适应的
    - flexible 灵活的
    - expandable 可扩展的
  - 短语
    - highly scalable 高度可扩展的
    - scalable solution 可扩展的解决方案
  - 例句
    - The system is highly scalable and can handle thousands of users at once. 这个系统具有高度的可扩展性，可以同时处理成千上万的用户。
  - 补充
